export const Sliderdb = [
  {
    heading: "Live Streaming Radio",
    desc: "Listen to latest hot music in uganda",
    image: "/images/slide1.jpg",
    label: "Get",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide2.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide3.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide4.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide5.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide6.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide7.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide8.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide9.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide10.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide11.jpg",
    label: "Check",
    path: "/top",
  },
  {
    heading: "Ubteb Results",
    desc: "Check for your Ubteb Results",
    image: "/images/slide12.jpg",
    label: "Check",
    path: "/top",
  },
];